title: traian-d blog
description: >- # this means to ignore newlines until "baseurl:"
  Projects, ideas and comments in machine learning, statistics and software engineering.
baseurl: ""
url: "http://traian-d.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
