title: "traian-d blog"
author: ""
description: >-
  Projects, ideas and comments in machine learning, statistics and software engineering.
url: "http://traian-d.github.io"
github_username: "traian-d"


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
