title: "traian-d blog"
author: ""
description: >-
  Things I find interesting.
url: "http://traian-d.github.io"
github_username: "traian-d"


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
